### ISSUE TITLE
项目源码可用的时机

### ISSUE THREAD

**Issue by huangwb8** [twelfth-star/LinkGPT#1]
我对Preprint《[LinkGPT: Teaching Large Language Models To Predict Missing Links](https://arxiv.org/abs/2406.04640)》所描述的方法颇有兴趣，想了解一下代码实现。

不知您是否准备开源项目代码？

**Comment by twelfth-star** [comment]
您好，感谢您对这篇文章的关注！前段时间我有点忙，因此最近才有空整理代码。现在项目源码已经上传，如果还有什么问题的话请随时提出。
