### ISSUE TITLE
 Issues installing DGL 2.0.0 with CUDA 11.7 support

### ISSUE THREAD

**Issue by William3242** [twelfth-star/LinkGPT#3]
Thank you for sharing this wonderful project. I am currently trying to set up the environment as specified, but I am encountering issues related to the installation of the DGL library version 2.0.0 with CUDA 11.6 support (`dgl==2.0.0+cu116`). It seems like this version is not available through the usual channels like conda or pip, which is preventing me from successfully running the training script.

I encountered the following error while executing the command bash scripts/amazon_clothing_20k/train_linkgpt.sh:

```
(linkgpt) wlhuang@ybcs:~/llm/LinkGPT$ bash scripts/amazon_clothing_20k/train_linkgpt.sh
Traceback (most recent call last):
  File "/home/wlhuang/llm/LinkGPT/linkgpt/train/train.py", line 286, in <module>
    main()
  File "/home/wlhuang/llm/LinkGPT/linkgpt/train/train.py", line 147, in main
    lp_dataset = basics.load_pickle(args.lp_dataset_path)
  File "/home/wlhuang/llm/LinkGPT/linkgpt/utils/basics.py", line 71, in load_pickle
    data = pickle.load(f)
ModuleNotFoundError: No module named 'dgl.heterograph'
```

It seems the issue is related to the missing DGL library, and I suspect that it's due to an incompatible or missing version of DGL. Could you please share the dgl==2.0.0+cu116 version or guide me on how to install it?
Here are some environment details:

Python version: 3.9

CUDA version: 11.7

Conda environment used: linkgpt

Any help regarding how to correctly set up the environment with the required DGL version would be greatly appreciated!

**Comment by twelfth-star** [comment]
Thank you for raising the issue. I installed DGL about a year ago, so the specific version might no longer be available via pip or conda. You could try downloading the corresponding `.whl` file for your Python version (in this case, 3.9) from [here](https://data.dgl.ai/wheels/cu116/repo.html) and install it locally.
![image](https://github.com/user-attachments/assets/6f509600-ed4a-40ff-b948-30ea93f21dbc)
